export const iconsConfig = {
  SXP: 'https://app.venus.io/coins/sxp.png',
  XVS: 'https://app.venus.io/coins/xvs.png',
  USDC: 'https://app.venus.io/coins/usdc.png',
  USDT: 'https://app.venus.io/coins/usdt.png',
  BUSD: 'https://app.venus.io/coins/busd.png',
  BNB: 'https://app.venus.io/coins/bnb.png',
  BTCB: 'https://app.venus.io/coins/btcb.png',
  ETH: 'https://app.venus.io/coins/eth.png',
  LTC: 'https://app.venus.io/coins/ltc.png',
  XRP: 'https://app.venus.io/coins/xrp.png',
  BCH: 'https://app.venus.io/coins/bch.png',
  DOT: 'https://app.venus.io/coins/dot.png',
  LINK: 'https://app.venus.io/coins/link.png',
  DAI: 'https://app.venus.io/coins/dai.png',
  FIL: 'https://app.venus.io/coins/fil.png',
  BETH: 'https://app.venus.io/coins/beth.png',
  ADA: 'https://app.venus.io/coins/ada.png',
  DOGE: 'https://app.venus.io/coins/doge.png',
  MATIC: 'https://app.venus.io/coins/matic.png',
  Cake: 'https://app.venus.io/coins/cake.png',
  AAVE: 'https://app.venus.io/coins/aave.png',
  TUSD: 'https://app.venus.io/coins/tusd.png',
  TRX: 'https://app.venus.io/coins/trx.png',
};
